networks:
  quiz-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:
  rabbit-data:
  minio-data:
  seq-data:

services:
  # MongoDB for Quiz.API
  quiz-db:
    image: mongo:7.0 # fixed version for consistency
    container_name: quiz-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=quiz_password
    volumes:
      - mongo-data:/data/db
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL for Grading and Certificate services 
  main-db:
    image: postgres:16-alpine
    container_name: main-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=main_password
      - POSTGRES_DB=QuizMasterDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d QuizMasterDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ (Message Broker) 
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP code port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 15s
      timeout: 10s
      retries: 5

  # S3 compatible storage for pdf sertifacation
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000" # API
      - "9001:9001" # controle console
    environment:
      - MINIO_ROOT_USER=admin   
      - MINIO_ROOT_PASSWORD=minio_password
    volumes:
      - minio-data:/data
    networks:
      - quiz-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=Y
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    networks:
      - quiz-network